#ifndef __AUDIO_TONEURI_H__
#define __AUDIO_TONEURI_H__

extern const char* tone_uri[];

typedef enum {
    TONE_TYPE_AKAIJI,
    TONE_TYPE_AXM_101,
    TONE_TYPE_AXM_102,
    TONE_TYPE_AXM_103,
    TONE_TYPE_AXM_104,
    TONE_TYPE_AXM_105,
    TONE_TYPE_AXM_106,
    TONE_TYPE_AXM_107,
    TONE_TYPE_AXM_108,
    TONE_TYPE_AXM_109,
    TONE_TYPE_AXM_110,
    TONE_TYPE_AXM_111,
    TONE_TYPE_AXM_112,
    TONE_TYPE_AXM_113,
    TONE_TYPE_AXM_114,
    TONE_TYPE_AXM_115,
    TONE_TYPE_AXM_116,
    TONE_TYPE_AXM_117,
    TONE_TYPE_AXM_118,
    TONE_TYPE_AXM_119,
    TONE_TYPE_AXM_120,
    TONE_TYPE_CL,
    TONE_TYPE_JEISUO,
    TONE_TYPE_OPEN,
    TONE_TYPE_SUODING,
    TONE_TYPE_MAX,
} tone_type_t;

int get_tone_uri_num();

#endif
